### ISSUE TITLE
Errors in MISC feature declarations

### ISSUE THREAD

**Issue by bguil** [UniversalDependencies/UD_Sanskrit-UFAL#5]
I found two lines with strange MISC data:

 * line 49: I suppose that the second `Translit` should be `LTranslit`
```
9	कुबेरः	कुबेर	PROPN	_	Case=Nom|Gender=Masc|Number=Sing	1	conj	_	Translit=kuberaḥ|Translit=kubera|Gloss=Kubera
```

 * line 3584: MISC features are separated by two pipe symbols 
```
5-6	पुररोधः	_	_	_	_	_	_	_	Translit=purarodhaḥ||Gloss=(siege-of-city)
```

**Comment by dan-zeman** [comment]
Thanks! Fixed in https://github.com/UniversalDependencies/UD_Sanskrit-UFAL/commit/1a745f25bafa2b3465055622de8ce7ed1f796ba6
